package net.sourceforge.jweb.mybatis.generator.plugins;
/*
 * Copyright 2002-2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import net.sourceforge.jweb.maven.util.XMLUtil;

import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.*;
import org.mybatis.generator.api.dom.xml.Document;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.logging.Log;
import org.mybatis.generator.logging.LogFactory;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

import java.io.StringReader;
import java.util.Date;
import java.util.List;
import java.util.Properties;

import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpression;

/**
 * Adds "selectOneByExample" method to the appropriate Mapper interface returning exactly one object instance.<br/>
 * Example configuration:<br/>
 * <tt>
 * <pre>
 * &lt;generatorConfiguration&gt;
 *  &lt;context ...&gt;
 *
 *      &lt;plugin type="net.sourceforge.jweb.mybatis.generator.plugins.SelectOneByExamplePlugin"/&gt;
 *      ...
 *
 *  &lt;/context&gt;
 * &lt;/generatorConfiguration&gt;
 * </pre>
 * </tt>
 * <br/> Properties:<br/> <ul> <li><strong>methodToGenerate</strong> (optional) : the name of the method to generate.
 * Default: <strong>selectOneByExample</strong></li> <li><strong>excludeClassNamesRegexp</strong> (optional): classes to
 * exclude from generation as regular expression. Default: none</li> </ul>
 */
public class SelectOneByExamplePlugin extends PluginAdapter {
	private final static Log LOG=LogFactory.getLog(SelectOneByExamplePlugin.class);
	
    private Config config;
    private boolean generateSelectOneWithBLOBs=true;
    private boolean generateSelectOneWithoutBLOBs=true;

    public boolean validate(List<String> warnings) {
        if (this.config == null){
        	this.config = new Config(getProperties());
        }
        return true;
    }

    @Override
    public boolean sqlMapDocumentGenerated(Document document, IntrospectedTable introspectedTable) {
    	//�ڲ���XML��ʱ������ibatis2��mybatis3ʵ�ֲ�ͬ���������Dom���Ƶ��취���
    	String xmlStr=document.getFormattedContent();
    	StringReader reader=new StringReader(xmlStr);
    	try {
    		org.w3c.dom.Document dom=XMLUtil.createDocument(reader);
			if(generateSelectOneWithBLOBs){
				XPathExpression exp=XMLUtil.compile("//select[@id='selectByExampleWithBLOBs']");
				Object nodeObj = exp.evaluate(dom, XPathConstants.NODESET);
				if(nodeObj!=null){
					NodeList nodes=(NodeList)nodeObj;
					if(nodes.getLength()!=1){
						LOG.warn("[WARN] find more than one selectByExampleWithBLOBs element, this is ambitious for SelectOneByExamplePlugin, ignored");
					}
					else {
						Element selectEl=(Element)nodes.item(0);
						document.getRootElement().addElement(new TextElement("<!-- generated by SelectOneByExamplePlugin "+new Date()+" -->"));
						org.mybatis.generator.api.dom.xml.XmlElement selectOneXmlEl=(org.mybatis.generator.api.dom.xml.XmlElement)PluginUtil.cloneElement(selectEl, config.methodToGenerate+"WithBLOBs");
						if(config.forceSelectOne) {
							selectOneXmlEl.addElement(new TextElement("limit 1"));
						}
						document.getRootElement().addElement(selectOneXmlEl);
					}
				}
	    	}
	    	if(generateSelectOneWithoutBLOBs){
	    		XPathExpression exp=XMLUtil.compile("//select[@id='selectByExample']");
	    		Object nodeObj = exp.evaluate(dom, XPathConstants.NODESET);
				if(nodeObj!=null){
					NodeList nodes=(NodeList)nodeObj;
					if(nodes.getLength()!=1){
						LOG.warn("[WARN] find more than one selectByExample element, this is ambitious for SelectOneByExamplePlugin, ignored");
					}
					else {
						Element selectEl=(Element)nodes.item(0);
						document.getRootElement().addElement(new TextElement("<!-- generated by SelectOneByExamplePlugin "+new Date()+" -->"));
						org.mybatis.generator.api.dom.xml.XmlElement selectOneXmlEl=(org.mybatis.generator.api.dom.xml.XmlElement)PluginUtil.cloneElement(selectEl, config.methodToGenerate);
						if(config.forceSelectOne) {
							selectOneXmlEl.addElement(new TextElement("limit 1"));
						}
						document.getRootElement().addElement(selectOneXmlEl);
					}
				}
	    	}
		} catch (Exception e) {
			e.printStackTrace();
		}
    	
        return true;
    }
    
    @Override
    public boolean clientSelectByExampleWithBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable) {
        if ((generateSelectOneWithBLOBs=!config.shouldExclude(interfaze.getType()))){
        	interfaze.addMethod(generateSelectOneByExample(method, introspectedTable, true));
        }

        return true;
    }

    @Override
    public boolean clientSelectByExampleWithoutBLOBsMethodGenerated(Method method, Interface interfaze,IntrospectedTable introspectedTable) {
        if ((generateSelectOneWithoutBLOBs=!config.shouldExclude(interfaze.getType()))){
        	interfaze.addMethod(generateSelectOneByExample(method, introspectedTable, false));
        }
        return true;
    }

    @Override
    public boolean clientSelectByExampleWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        if ((generateSelectOneWithBLOBs=!config.shouldExclude(topLevelClass.getType()))){
        	topLevelClass.addMethod(generateSelectOneByExample(method, introspectedTable, true));
        }
        return true;
    }

    @Override
    public boolean clientSelectByExampleWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        if ((generateSelectOneWithoutBLOBs=!config.shouldExclude(topLevelClass.getType()))){
        	topLevelClass.addMethod(generateSelectOneByExample(method, introspectedTable, false));
        }
        return true;
    }
    /*
     * ��.java�ļ������SelectOneByExample��SelectOneByExampleWithBLOBs
     */
    private Method generateSelectOneByExample(Method method, IntrospectedTable introspectedTable, boolean withBLOBs) {
        Method m = new Method(config.methodToGenerate+(withBLOBs?"WithBLOBs":""));
        m.setVisibility(method.getVisibility());
        FullyQualifiedJavaType returnType = introspectedTable.getRules().calculateAllFieldsClass();
        m.setReturnType(returnType);
        List<String> annotations = method.getAnnotations();
        for (String a : annotations) {
            m.addAnnotation(a);
        }
        List<Parameter> params = method.getParameters();
        for (Parameter p : params) {
            m.addParameter(p);
        }
        context.getCommentGenerator().addGeneralMethodComment(m, introspectedTable);
        return m;
    }

    private static final class Config extends BasePluginConfig {
        private static final String defaultMethodToGenerate = "selectOneByExample";
        private static final String methodToGenerateKey = "methodToGenerate";

        private String methodToGenerate;
        private boolean forceSelectOne;//add limit 1 to make sure select one
        protected Config(Properties props) {
            super(props);
            this.methodToGenerate = props.getProperty(methodToGenerateKey, defaultMethodToGenerate);
            this.forceSelectOne=Boolean.getBoolean(props.getProperty("forceSelectOne", "false"));
        }
    }
   
}
